version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ai-generator-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  backend:
    build: ./backend
    container_name: ai-generator-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./cotti-coffee-462402-96fb1983df3e.json:/app/cotti-coffee-462402-96fb1983df3e.json
      - ./.env:/app/.env

  frontend:
    build: ./frontend
    container_name: ai-generator-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  redis_data: